CREATE TABLE Person (
  person_id BIGSERIAL,
  age INTEGER NOT NULL,
  bio VARCHAR(64) NOT NULL,
  fullName VARCHAR(64) NOT NULL,
  nickname VARCHAR(30) NOT NULL,
  number_of_posts INTEGER NOT NULL
);

ALTER TABLE Person ADD CONSTRAINT pkPerson
  PRIMARY KEY (person_id);

ALTER TABLE Person ADD CONSTRAINT unqNickname UNIQUE (nickname);
ALTER TABLE Person ADD CONSTRAINT noPosts DEFAULT 0;